# -*- coding: utf-8 -*-
"""Plant Disease Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypKNq_yLWrv-06ml3ikATlkSETMs-9T2
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import kagglehub

# Download latest version
path = kagglehub.dataset_download("karagwaanntreasure/plant-disease-detection")

print("Path to dataset files:", path)

import os

dataset_path = path

print("Main folders:")
print(os.listdir(dataset_path))

for root, dirs, files in os.walk(dataset_path):
    print("Current folder:", root)
    print("Subfolders:", dirs[:10])
    print("Number of files:", len(files))
    print("-" * 50)
    break

for folder in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder)
    if os.path.isdir(folder_path):
        print(folder, ":", len(os.listdir(folder_path)))

import os

dataset_path = path + "/Dataset"

classes = os.listdir(dataset_path)

print("Number of classes:", len(classes))
print("Classes:")
print(classes)

print("\nImages per class:")
for class_name in classes:
    class_path = os.path.join(dataset_path, class_name)
    if os.path.isdir(class_path):
        print(class_name, ":", len(os.listdir(class_path)))

import matplotlib.pyplot as plt
from PIL import Image
import random

class_name = random.choice(classes)
class_path = os.path.join(dataset_path, class_name)

image_name = random.choice(os.listdir(class_path))
image_path = os.path.join(class_path, image_name)

img = Image.open(image_path)

plt.imshow(img)
plt.title(class_name)
plt.axis("off")

import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_data = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_data = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_data.class_names

print("Classes:", class_names)
print("Number of classes:", len(class_names))

AUTOTUNE = tf.data.AUTOTUNE

train_data = train_data.prefetch(buffer_size=AUTOTUNE)
val_data = val_data.prefetch(buffer_size=AUTOTUNE)

from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2

NUM_CLASSES = len(class_names)

base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

model = models.Sequential([
    layers.Rescaling(1./255),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

EPOCHS = 5

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=EPOCHS
)

import numpy as np
from tensorflow.keras.preprocessing import image
from PIL import Image
import matplotlib.pyplot as plt

img_path = image_path

img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)


prediction = model.predict(img_array)

predicted_class = class_names[np.argmax(prediction)]
confidence = np.max(prediction)

print("Prediction:", predicted_class)
print("Confidence:", confidence)

plt.imshow(Image.open(img_path))
plt.title(f"{predicted_class} - {confidence:.2%}")
plt.axis("off")

model.save("plant_disease_model.keras")

import json

with open("class_names.json", "w") as f:
    json.dump(class_names, f)

from google.colab import files

files.download("plant_disease_model.keras")
files.download("class_names.json")

!pip install gradio -q

import gradio as gr
import tensorflow as tf
import numpy as np
import json
from PIL import Image

# Load model
model = tf.keras.models.load_model("plant_disease_model.keras")

# Load class names
with open("class_names.json", "r") as f:
    class_names = json.load(f)

# Recommendations
recommendations = {
    "healthy": "✅ The plant appears healthy. Keep regular watering, provide enough sunlight, and monitor the leaves weekly.",
    "default": "⚠️ Remove infected leaves, avoid overhead watering, improve air circulation, and consult an agricultural specialist if symptoms spread."
}

def format_class_name(class_name):
    return class_name.replace("___", " - ").replace("__", " ").replace("_", " ")

def get_status(predicted_class, confidence):
    if "healthy" in predicted_class.lower():
        return "✅ Healthy Plant", "The plant looks healthy based on the uploaded image."
    elif confidence < 0.60:
        return "⚠️ Low Confidence", "The model is not fully confident. Try uploading a clearer leaf image."
    else:
        return "🚨 Disease Detected", "The uploaded leaf may show signs of disease."

def predict_image(img):
    if img is None:
        return (
            "No image uploaded",
            "0%",
            "Please upload a clear leaf image first.",
            "No predictions available.",
            "⚠️ Waiting for image",
            "Upload an image to start analysis."
        )

    img = img.convert("RGB")
    img = img.resize((224, 224))

    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    predicted_index = np.argmax(prediction)
    predicted_class = class_names[predicted_index]
    confidence = float(np.max(prediction))

    clean_name = format_class_name(predicted_class)
    confidence_text = f"{confidence * 100:.2f}%"

    status, description = get_status(predicted_class, confidence)

    if "healthy" in predicted_class.lower():
        recommendation = recommendations["healthy"]
    elif confidence < 0.60:
        recommendation = "Please upload a clearer image with one leaf visible, good lighting, and minimal background noise."
    else:
        recommendation = recommendations["default"]

    top_indices = prediction[0].argsort()[-3:][::-1]
    top_3 = ""
    for rank, i in enumerate(top_indices, start=1):
        top_3 += f"{rank}. {format_class_name(class_names[i])}: {prediction[0][i] * 100:.2f}%\n"

    return clean_name, confidence_text, recommendation, top_3, status, description


custom_css = """
.gradio-container {
    max-width: 1200px !important;
    margin: auto !important;
}

#title {
    text-align: center;
    margin-bottom: 10px;
}

#subtitle {
    text-align: center;
    font-size: 17px;
    margin-bottom: 25px;
}

.result-card {
    padding: 16px;
    border-radius: 14px;
}
"""

with gr.Blocks(
    theme=gr.Theme.from_hub("miittnnss/green"),
    css=custom_css
) as demo:

    gr.Markdown(
        """
        # 🌿 Plant Disease Detection AI
        """,
        elem_id="title"
    )

    gr.Markdown(
        """
        Upload a clear leaf image and let the AI detect possible plant disease with confidence and care recommendations.
        """,
        elem_id="subtitle"
    )

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                type="pil",
                label="Upload Leaf Image",
                height=420
            )

            predict_btn = gr.Button(
                "🔍 Analyze Image",
                variant="primary"
            )

            gr.Markdown(
                """
                **Tips for better results:**
                - Use a clear leaf image
                - Avoid blurry photos
                - Try to show one main leaf
                - Good lighting improves prediction
                """
            )

        with gr.Column(scale=1):
            status_output = gr.Textbox(
                label="Analysis Status",
                lines=1
            )

            description_output = gr.Textbox(
                label="Result Summary",
                lines=2
            )

            prediction_output = gr.Textbox(
                label="Predicted Disease",
                lines=1
            )

            confidence_output = gr.Textbox(
                label="Confidence",
                lines=1
            )

            recommendation_output = gr.Textbox(
                label="Recommendation",
                lines=4
            )

            top3_output = gr.Textbox(
                label="Top 3 Predictions",
                lines=4
            )

    gr.Markdown(
        """
        ---
        ⚠️ **Disclaimer:** This tool is for educational and demonstration purposes only.
        For real agricultural decisions, consult a plant disease or agricultural specialist.
        """
    )

    predict_btn.click(
        fn=predict_image,
        inputs=image_input,
        outputs=[
            prediction_output,
            confidence_output,
            recommendation_output,
            top3_output,
            status_output,
            description_output
        ]
    )

demo.launch(debug=True, share=True)
